FROM ubuntu:20.04

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=GMT

# Update package lists and the install necessary packages
RUN apt-get update && apt-get install -y \
    curl \
    emacs \
    gcc \
    gdb \
    git \
    htop \
    python3 \
    python3-pip \
    tree \
    vim \
    wget
	
# Install pydocstyle
RUN pip3 install pydocstyle

# Clone the Betty repository and run the install.sh script
RUN git clone https://github.com/alx-tools/Betty.git /opt/betty && \
    chmod +x /opt/betty/install.sh && \
    /opt/betty/install.sh